name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm install
      
    - name: Build documentation
      run: npm run build:docs
      
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        
        # Set up remote with proper token
        git remote set-url origin https://x-access-token:${{ secrets.GH_PAGES_TOKEN }}@github.com/${{ github.repository }}
        
        # Create or checkout gh-pages branch
        if ! git show-ref --verify --quiet refs/heads/gh-pages; then
          echo "Creating new gh-pages branch"
          git checkout --orphan gh-pages
          git rm -rf . || true
        else
          echo "Checking out existing gh-pages branch"
          git checkout gh-pages
        fi
        
        # Only add files needed for GitHub Pages (exclude node_modules, benchmarks, etc.)
        git add index.html *.html
        git add -f package.json package-lock.json
        git add -f tsconfig.json
        git add -f README.md GETTING_STARTED.md BENCHMARK_GUIDE.md SUMMARY.md
        
        # Commit and push
        git commit -m "Deploy to GitHub Pages - $(date)" || exit 0
        git push origin gh-pages
